
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/birdfarm_swp391?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

testcontainers:
  db-scripts: sql/db.sql